result_folder: 128_128_Gaussian_Noise_30/
model_epoch: 99
batch_size: 1
with_mask: true
strength_factor: 1
# noise_layer: DiffJPEG(differentiable=True, quality=50)
# noise_layer: GaussianNoiseEditGuard(noisesigma=1)
noise_layer: PoissonNoise()

# Identity()/JpegTest()/Resize()/GaussianBlur()/MedianBlur()/Brightness()/Contrast()/Saturation()/Hue()/FaceCrop()/FaceCropout()/Dropout()/SaltPepper()/GaussianNoise()
# FaceErase()/FaceEraseout()/SimSwap()/FaceSwap()/GANimation()/StarGAN()
